// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtP_y6POLTbdR6UDuAZNMXDMVmo39FnYA',
    appId: '1:351744294113:web:bcc5c9fc10aa80c2fdcba0',
    messagingSenderId: '351744294113',
    projectId: 'chatapp-2804e',
    authDomain: 'chatapp-2804e.firebaseapp.com',
    storageBucket: 'chatapp-2804e.firebasestorage.app',
    measurementId: 'G-R8R7XQNYYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKUxK_mdyh_CoQsrUs04HMhN7Ten7FBPs',
    appId: '1:351744294113:android:47ac503ebc8a752bfdcba0',
    messagingSenderId: '351744294113',
    projectId: 'chatapp-2804e',
    storageBucket: 'chatapp-2804e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYpsfklCmiY3e-8LbbMAE9InE5_DAcOiI',
    appId: '1:351744294113:ios:6d2dd1070414cbe7fdcba0',
    messagingSenderId: '351744294113',
    projectId: 'chatapp-2804e',
    storageBucket: 'chatapp-2804e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYpsfklCmiY3e-8LbbMAE9InE5_DAcOiI',
    appId: '1:351744294113:ios:6d2dd1070414cbe7fdcba0',
    messagingSenderId: '351744294113',
    projectId: 'chatapp-2804e',
    storageBucket: 'chatapp-2804e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtP_y6POLTbdR6UDuAZNMXDMVmo39FnYA',
    appId: '1:351744294113:web:817c8b982de6443cfdcba0',
    messagingSenderId: '351744294113',
    projectId: 'chatapp-2804e',
    authDomain: 'chatapp-2804e.firebaseapp.com',
    storageBucket: 'chatapp-2804e.firebasestorage.app',
    measurementId: 'G-19EQEK7JFV',
  );

}